#!/bin/sh

# 1) Get the list of changed files in the last merge
changed_files=$(git diff --name-only ORIG_HEAD HEAD)

# 2) Check if dev_psa.txt had changes
if echo "$changed_files" | grep -q "dev_psa.txt"; then
  printf "\e[0;31m" && cat dev_psa.txt
fi
